site_name: pyImx
site_description: IMX related Python packages
use_directory_urls: false

# https://github.com/danielfrg/mkdocs-jupyter
theme:
  name: 'material'
  custom_dir: docs-overrides
  palette:
    - scheme: default
      primary: 'red'
      accent: 'red'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: 'red'
      accent: 'red'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    logo: material/account-supervisor
  favicon: 'favicon.png'
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.annotate

repo_name: Movares.PyImx
repo_url: https://movares-ta.visualstudio.com/ReDesign/_git/Movares.PyImx
edit_uri: ""

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - tables
  - def_list

plugins:
  - search
  - mike
  - mkdocs-jupyter:
      theme: dark
      include_source: True
  - mkdocstrings:
      watch:
      - pyImx

extra:
  version:
    provider: mike

nav:
  - About: about.md
  - Used cases:
      - Notebooks:
        - Notebook page: notebooks/PI-demo-pyImx.ipynb
        - Notebook page: notebooks/PI-demo-opleveringsklaar-maken.ipynb
        - Notebook page: notebooks/PI-demo-integraties.ipynb
  - Vision and Roadmap:
    - Vision: vision.md
    - Roadmap: roadmap.md
  - Examples:
    - examples/Imx-example.md
    - examples/ImxBim-example.md
    - examples/ImxDiff-example.md
  - Reference:
      - pyImx:
        - Imx: pyImx/imx.md
        - ImxDict: pyImx/imxDict.md
        - ImxValueObjects: pyImx/valueObjects.md
      - pyImxBim:
          - ImxBim: pyImx/bim.md
      - pyImxDiff:
        - ImxDiff: pyImxDiff/imxDiff.md
        - Diff operators: pyImxDiff/customOperators.md
        # - ImxDiffReport: pyImxDiff/imxDiffReporter.md
  - Get Involved: contribute.md
  - Jupyter Lab: jupyter-lab.md
