name: Reusable workflow example

on:
  workflow_dispatch:
  
jobs:
  install-test-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Install python and dependencies
      uses: ./.github/workflows/python-install.yml
      with:
        matrix: matrix
      
    - name: Test package
      uses: ./.github/workflows/package-test.yml  
