name: Reusable workflow example

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Package test]
    types: [completed]
    
jobs:
  install-test-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        
    steps:
    - uses: actions/checkout@v3
