name: Package test
 
on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check codestyle
      run: |
        make format-check
        make lint
        
    - name: Typecheck
      continue-on-error: true
      run: |
         make typecheck

    - name: Test with pytest
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
         pytest --cov=shapelyM/
         codecov
