name: Publish to PyPI.org
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flit
          flit install --deps develop
      - name: Test with pytest
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          run: |
            pytest --cov=shapelyM/
            codecov
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}