name: Do things every 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'


jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '*/10 * * *'
        run: echo "This step will be visable on 10th min"
      - name: Every time
        run: echo "This step will always run"
